package com.cjglib.crud.bean;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn1_dept.dept_id
     *
     * @mbg.generated Tue Mar 20 14:46:23 CST 2018
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tn1_dept.dept_name
     *
     * @mbg.generated Tue Mar 20 14:46:23 CST 2018
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn1_dept.dept_id
     *
     * @return the value of tn1_dept.dept_id
     *
     * @mbg.generated Tue Mar 20 14:46:23 CST 2018
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn1_dept.dept_id
     *
     * @param deptId the value for tn1_dept.dept_id
     *
     * @mbg.generated Tue Mar 20 14:46:23 CST 2018
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tn1_dept.dept_name
     *
     * @return the value of tn1_dept.dept_name
     *
     * @mbg.generated Tue Mar 20 14:46:23 CST 2018
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tn1_dept.dept_name
     *
     * @param deptName the value for tn1_dept.dept_name
     *
     * @mbg.generated Tue Mar 20 14:46:23 CST 2018
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}